### ISSUE TITLE
The compliance tool brings inconsistent results depending on file ordering

### ISSUE THREAD

**Issue by stof** [php-pds/skeleton_research#1]
When checking for files or directories, the tool checks all lines one by one and does the following:

- if the line matches the expected name, return true
- if the line matches a failure case, return false

But this means that if a package contains both the expected file and another file matching a failure case, the compliance result depends on the order in which these files are processed (the first processed file will end the analysis). As the order used by scandir is the alphabetical order, it means that the result is at least deterministic, but still flawed. Here is an example:

- having both ``CONTRIBUTING.md`` and ``README.CONTRIBUTING.md`` is considered compliant
- having both ``CONTRIBUTING.md`` and ``CONTRIBUTE.md`` is considered not compliant

I don't know how many packages are impacted by this flaw (and I suspect that the CONTRIBUTING file is unlikely to have such duplicate files, but others sections might be impacted).

**Comment by pmjones** [comment]
Good thinking.

I just did a quick check, changing "return true" to "continue" in checkDir() and checkFile(); each still returns "true" if it gets past all the known non-compliant names. Across the larger set of packages (110k+), the previous "tentative compliance" count was 78078. With the change, it is slightly less, at 77790; so, only 288 packages are dropped from the results.

I'll update the compliance script and the reported compliance numbers.

**Comment by pmjones** [comment]
@stof While the compliance script is update per your above notes, you have other issues open that will affect the reporting numbers. When those are all resolved, I will update the report.
