### ISSUE TITLE
[Suggestion] Include Tests with a capital letter in the analysis about test folders

### ISSUE THREAD

**Issue by stof** [php-pds/skeleton_research#3]
This is the second most common directory name for tests, after ``tests`` but before ``test``

**Comment by pmjones** [comment]
The presumption here is that directories starting with a capital letter are representative of a PHP namespace, and so are excluded. The only known exception is capital-R "Resources", which I have been informed is a Symfony-ism that does not represent a namespace. If capital-T "Tests" (which also looks like a Symfony-ism) is *not* intended to represent a PHP namespace, let me know.

**Comment by pmjones** [comment]
After looking through these, it does appear that capital-T "Tests" represents a namespace, and as such is not counted per the existing methodology. Let me know if you find otherwise.
