### ISSUE TITLE
More folder names should be considered for types

### ISSUE THREAD

**Issue by stof** [php-pds/skeleton_research#4]
This is found while looking at the list of other directories:

CSS preprocessors (might be discussed between resources and public as they don't need to be public depending on the setup):

- ``less``
- ``sass``
- ``scss``

Other public folders:

- ``javascripts``
- ``icons``
- ``imgs``
- ``wwwroot``
- ``font``

Other source folders:

- ``src-dev``

Other doc folders:

- ``apidocs``
- ``apidoc``
- ``api-reference``
- ``user_guide``
- ``manuals``
- ``phpdocs``

Other test folders:

- ``unittest``
- ``unit_tests``
- ``unit_test``
- ``phpunit-tests``
- ``spec`` (for PhpSpec users), even though this may not disqualify a package to be compliant, as PhpSpec specs are not primarily tests

These are not among the commonly used names, so they should not alter the final decision, but they might be worth taking into account for the compliance tool (which needs to list non-compliant alternatives) and in the stats about the amount of package using each group.

**Comment by pmjones** [comment]
Although the compliance check is intended as a "tentative" compliance, more accuracy is better. If you send a PR with those additions to the compliance script, and/or other code as needed, I'll be happy to review it. Thanks!

**Comment by pmjones** [comment]
@stof If you are already working up a PR on this let me know; otherwise, I'll address it myself.

**Comment by pmjones** [comment]
This is applied in https://github.com/php-pds/skeleton_research/commit/fab33c93d3e20f9b36089ec87ef1bd84b168f99d . Let me know if you think of anything else, and thanks for your attention to detail!
